# Pytorch (Tensors Practice)

## Importing

In [ ]:
import torch
print(torch.__version__)

2.9.0+cu126


## Checking the Availability of Cuda

In [ ]:
if torch.cuda.is_available():
  print("GPU is Available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU.")

GPU is Available!
Using GPU: Tesla T4


### Using GPU

In [ ]:
if torch.cuda.is_available():
  device = torch.device('cuda')
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  device = torch.device('cpu')
  print("GPU not available. Using CPU.")

Using GPU: Tesla T4


In [ ]:
# Creating a Tensor in GPU (VRAM)
torch.rand((2,3),device=device)

tensor([[0.3966, 0.4855, 0.8226],
        [0.3215, 0.4935, 0.4545]], device='cuda:0')

In [ ]:
# Migrating a Tensor from CPU to GPU
x = torch.rand(2,3)
print(x)
y = x.to(device)
print(y)

tensor([[0.8847, 0.7430, 0.0602],
        [0.6701, 0.7538, 0.9341]])
tensor([[0.8847, 0.7430, 0.0602],
        [0.6701, 0.7538, 0.9341]], device='cuda:0')


In [ ]:
# CPU VS GPU
import torch
import time

size = 10000

# Creating Random large matrices in CPU
m1_cpu = torch.rand(size,size)
m2_cpu = torch.rand(size,size)

# Checking Time of Matrix Multiplication on CPU
st = time.time()
result = m1_cpu @ m2_cpu
cpu_time = time.time() - st

print(f"CPU Took {cpu_time:.4f} seconds")

# Moving Matrices to GPU
m1_gpu = m1_cpu.to('cuda')
m2_gpu = m2_cpu.to('cuda')

# Checking Time of Matrix Multiplication on GPU
st = time.time()
result = m1_gpu @ m2_gpu
torch.cuda.synchronize()  # Wait for all gpu kernels to complete operations
gpu_time = time.time() - st

print(f"GPU Took {gpu_time:.4f} seconds")


CPU Took 15.0867 seconds
GPU Took 0.5322 seconds


## Creation of Tensors

In [ ]:
# .empty function just boundaries the existing memory for our
# tensor use according to the shape we provide. The memory
# will not be initialized and will be containing either garbage
# value or the value previouslty contained by that memory
first_tensor = torch.empty(2,3)

In [ ]:
type(first_tensor)

torch.Tensor

In [ ]:
# .zeros function make the tensor of desired shape but initialize
# the tensor completely with zeros.
torch.zeros(2,3)
# It can be used when we need to make a BIAS tensor but initialized
# with zeros because it will be updated in runtime.

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# .ones function make the tensor of desired shape but initialize
# the tensor completely with ones.
torch.ones(2,3)
# It can be used when we need to make a BIAS tensor but initialized
# with ones that might be used as it is.

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# .rand function make the tensor of desired shape but initialize
# the tensor with values ranging from 0 -> 1.
torch.rand(2,3)
# It is good when we will be making the tensor for initially random
# weights and other such things.

tensor([[0.4528, 0.1168, 0.5575],
        [0.9937, 0.6152, 0.9297]])

In [ ]:
# manual_seed function defines the seed for the random value across all devices
# which is a number against which the random values remains same
# every time and every where
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# .tensor method is like a constructor which can make a tensor using
# any other data type like tuple, list etc.
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# Similar to the arange function of numpy which creates a tensor
# defined by range like 0 -> 10 and step means numbers to skip
# like 1 (default) or 2
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [ ]:
# Similar to the linspace function of numpy which creates a tensor
# defined by range like 0 -> 10 and step means number of elements
# to create (not like arange) like 10 or 20
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [ ]:
# To create an IDENTITY Tensor of required size
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
# .full function is to create a tensor for desired Size like (2,3)
# with the filling of elements values as described by the 2nd parameted
torch.full((2,3), 5)

tensor([[5, 5, 5],
        [5, 5, 5]])

## Data Types

**NOTE: Tensors are static datatype structues**

In [ ]:
# .dtype is an attribute which tells us the datatype of our overall
# tensor
x.dtype

torch.int64

In [ ]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Shapes of Tensors

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [ ]:
# .empty_like function lets us create a new tensor of the same size
# as that of provided tensor.
# Tensor creation will be similar to .empty method
y = torch.empty_like(x)
y

tensor([[              0,               0,               0],
        [            113, 132617899183328,       564258704]])

In [ ]:
# .zeros_like function lets us create a new tensor of the same size
# as that of provided tensor.
# Tensor creation will be similar to .zeros method
y = torch.zeros_like(x)
y

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
# .ones_like function lets us create a new tensor of the same size
# as that of provided tensor.
# Tensor creation will be similar to .ones method
y = torch.ones_like(x)
y

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
# .rand_like function lets us create a new tensor of the same size
# as that of provided tensor.
# Tensor creation will be similar to .rand method
# Both Below Methods are Good and Workable
y = torch.rand_like(x.to(torch.float32))
y = torch.rand_like(x, dtype=torch.float32)
y

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

## Mathematical Operations

### Integer Operations

In [ ]:
x
# Addition
print(x + 2)
# Substraction
print(x - 2)
# Multiplication
print(x * 3)
# Division (Normal)
print(x / 3)
# Division (Strict Integer)
print((x*100) // 3)
# Mod
print(((x*100) // 3)%2)
# Power
print(x**4)

tensor([[3, 4, 5],
        [6, 7, 8]])
tensor([[-1,  0,  1],
        [ 2,  3,  4]])
tensor([[ 3,  6,  9],
        [12, 15, 18]])
tensor([[0.3333, 0.6667, 1.0000],
        [1.3333, 1.6667, 2.0000]])
tensor([[ 33,  66, 100],
        [133, 166, 200]])
tensor([[1, 0, 0],
        [1, 0, 0]])
tensor([[   1,   16,   81],
        [ 256,  625, 1296]])


### Element Wise Operations on tensors of same size

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])
tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])


In [ ]:
# All Below Operations will be done Element Wise
# Add
print(a + b)
# Subtraction
print(a-b)
# Multiplication
print(a*b)
# Division
print(a / b)
# Power
print(a**b)
# Mod
print(a%b)

tensor([[0.6679, 1.2502, 0.9229],
        [1.3130, 0.7983, 1.6774]])
tensor([[-0.2201, -0.6455, -0.5661],
        [ 0.3346,  0.3132,  0.2767]])
tensor([[0.0994, 0.2866, 0.1328],
        [0.4030, 0.1348, 0.6842]])
tensor([[0.5042, 0.3190, 0.2397],
        [1.6841, 2.2912, 1.3951]])
tensor([[0.5145, 0.3218, 0.2771],
        [0.9096, 0.8672, 0.9839]])
tensor([[0.2239, 0.3023, 0.1784],
        [0.3346, 0.0706, 0.2767]])


In [ ]:
c = torch.tensor([1,-2,3,-4])

In [ ]:
# Absolute
print(torch.abs(c))
# Negative
print(torch.neg(c))

tensor([1, 2, 3, 4])
tensor([-1,  2, -3,  4])


In [ ]:
d = torch.tensor([1.0,2.3,4.9,5.6])

In [ ]:
# Rounding
print(d.round())
print(torch.round(d))

tensor([1., 2., 5., 6.])
tensor([1., 2., 5., 6.])


In [ ]:
# Ceil Function
print(d.ceil())
print(torch.ceil(d))

tensor([1., 3., 5., 6.])
tensor([1., 3., 5., 6.])


In [ ]:
# Floor Function
print(d.floor())
print(torch.floor(d))

tensor([1., 2., 4., 5.])
tensor([1., 2., 4., 5.])


In [ ]:
# Clamp Function - To get all the elements of tensor within defined
# min max range. The element smaller than min gets the min as swapped value
# similarly the elements greater than max gets the max as swapped value.
print(d.clamp(2,3))
print(torch.clamp(d,min=2,max=3))

tensor([2.0000, 2.3000, 3.0000, 3.0000])
tensor([2.0000, 2.3000, 3.0000, 3.0000])


### Reduction Operations
  Reducing the Tensors mostly upto a single value

In [ ]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[3., 3., 1.],
        [5., 6., 9.]])

In [ ]:
# Summing the Complete Tensor
print(e.sum())
print(torch.sum(e))
# Summing the Complete Tensor Column Wise
print(e.sum(dim=0))
print(torch.sum(e,dim=0))
# Summing the Complete Tensor Row Wise
print(e.sum(dim=1))
print(torch.sum(e,dim=1))

tensor(27.)
tensor(27.)
tensor([ 8.,  9., 10.])
tensor([ 8.,  9., 10.])
tensor([ 7., 20.])
tensor([ 7., 20.])


In [ ]:
# Mean of the Complete Tensor
print(e.mean())
print(torch.mean(e))
# Mean of the Complete Tensor Column Wise
print(e.mean(dim=0))
print(torch.mean(e,dim=0))
# Mean of the Complete Tensor Row Wise
print(e.mean(dim=1))
print(torch.mean(e,dim=1))

tensor(4.5000)
tensor(4.5000)
tensor([4.0000, 4.5000, 5.0000])
tensor([4.0000, 4.5000, 5.0000])
tensor([2.3333, 6.6667])
tensor([2.3333, 6.6667])


In [ ]:
# Median of the Complete Tensor
print(e.median())
print(torch.median(e))
# Median of the Complete Tensor Column Wise
print(e.median(dim=0))
print(torch.median(e,dim=0))
# Median of the Complete Tensor Row Wise
print(e.median(dim=1))
print(torch.median(e,dim=1))

tensor(3.)
tensor(3.)
torch.return_types.median(
values=tensor([3., 3., 1.]),
indices=tensor([0, 0, 0]))
torch.return_types.median(
values=tensor([3., 3., 1.]),
indices=tensor([0, 0, 0]))
torch.return_types.median(
values=tensor([3., 6.]),
indices=tensor([0, 1]))
torch.return_types.median(
values=tensor([3., 6.]),
indices=tensor([0, 1]))


In [ ]:
# Min of the Complete Tensor
print(e.min())
print(torch.min(e))
# Min of the Complete Tensor Column Wise
print(e.min(dim=0))
print(torch.min(e,dim=0))
# Min of the Complete Tensor Row Wise
print(e.min(dim=1))
print(torch.min(e,dim=1))

tensor(1.)
tensor(1.)
torch.return_types.min(
values=tensor([3., 3., 1.]),
indices=tensor([0, 0, 0]))
torch.return_types.min(
values=tensor([3., 3., 1.]),
indices=tensor([0, 0, 0]))
torch.return_types.min(
values=tensor([1., 5.]),
indices=tensor([2, 0]))
torch.return_types.min(
values=tensor([1., 5.]),
indices=tensor([2, 0]))


In [ ]:
# Max of the Complete Tensor
print(e.max())
print(torch.max(e))
# Max of the Complete Tensor Column Wise
print(e.max(dim=0))
print(torch.max(e,dim=0))
# Max of the Complete Tensor Row Wise
print(e.max(dim=1))
print(torch.max(e,dim=1))

tensor(9.)
tensor(9.)
torch.return_types.max(
values=tensor([5., 6., 9.]),
indices=tensor([1, 1, 1]))
torch.return_types.max(
values=tensor([5., 6., 9.]),
indices=tensor([1, 1, 1]))
torch.return_types.max(
values=tensor([3., 9.]),
indices=tensor([0, 2]))
torch.return_types.max(
values=tensor([3., 9.]),
indices=tensor([0, 2]))


In [ ]:
# Product of the Complete Tensor (Element got multiplyied by themselves all to all)
print(e.prod())
print(torch.prod(e))
# Product of the Complete Tensor Column Wise
print(e.prod(dim=0))
print(torch.prod(e,dim=0))
# Product of the Complete Tensor Row Wise
print(e.prod(dim=1))
print(torch.prod(e,dim=1))

tensor(2430.)
tensor(2430.)
tensor([15., 18.,  9.])
tensor([15., 18.,  9.])
tensor([  9., 270.])
tensor([  9., 270.])


In [ ]:
# Standard Deviation of the Complete Tensor
print(e.std())
print(torch.std(e))
# Standard Deviation of the Complete Tensor Column Wise
print(e.std(dim=0))
print(torch.std(e,dim=0))
# Standard Deviation of the Complete Tensor Row Wise
print(e.std(dim=1))
print(torch.std(e,dim=1))

tensor(2.8107)
tensor(2.8107)
tensor([1.4142, 2.1213, 5.6569])
tensor([1.4142, 2.1213, 5.6569])
tensor([1.1547, 2.0817])
tensor([1.1547, 2.0817])


In [ ]:
# Variance of the Complete Tensor
print(e.var())
print(torch.var(e))
# Variance of the Complete Tensor Column Wise
print(e.var(dim=0))
print(torch.var(e,dim=0))
# Variance of the Complete Tensor Row Wise
print(e.var(dim=1))
print(torch.var(e,dim=1))

tensor(7.9000)
tensor(7.9000)
tensor([ 2.0000,  4.5000, 32.0000])
tensor([ 2.0000,  4.5000, 32.0000])
tensor([1.3333, 4.3333])
tensor([1.3333, 4.3333])


In [ ]:
# Max Value Index of the Complete Tensor
print(e.argmax())
print(torch.argmax(e))
# Max Value Index of the Complete Tensor Column Wise
print(e.argmax(dim=0))
print(torch.argmax(e,dim=0))
# Max Value Index of the Complete Tensor Row Wise
print(e.argmax(dim=1))
print(torch.argmax(e,dim=1))

tensor(5)
tensor(5)
tensor([1, 1, 1])
tensor([1, 1, 1])
tensor([0, 2])
tensor([0, 2])


In [ ]:
# Min Value Index of the Complete Tensor
print(e.argmin())
print(torch.argmin(e))
# Min Value Index of the Complete Tensor Column Wise
print(e.argmin(dim=0))
print(torch.argmin(e,dim=0))
# Min Value Index of the Complete Tensor Row Wise
print(e.argmin(dim=1))
print(torch.argmin(e,dim=1))

tensor(2)
tensor(2)
tensor([0, 0, 0])
tensor([0, 0, 0])
tensor([2, 0])
tensor([2, 0])


In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)
print(f)
print(g)

tensor([[1, 7, 4],
        [9, 3, 4]])
tensor([[5, 4],
        [2, 0],
        [8, 6]])


In [ ]:
# Matrix Multiplication
print(f @ g)
torch.matmul(f,g)


tensor([[51, 28],
        [83, 60]])


tensor([[51, 28],
        [83, 60]])

In [ ]:
# Dot Product
vec1 = torch.tensor([1,2])
vec2 = torch.tensor([3,4])
print(vec1*vec2)  # Note Element Wise Multiplication (Not Dot Product)
print(vec1.dot(vec2))
print(torch.dot(vec1,vec2))

tensor([3, 8])
tensor(11)
tensor(11)


In [ ]:
# Transpose of Tensor
print(f.T)
print(torch.transpose(f,dim0=1,dim1=0))

tensor([[1, 9],
        [7, 3],
        [4, 4]])
tensor([[1, 9],
        [7, 3],
        [4, 4]])


In [ ]:
h = torch.randint(0,100,(3,3),dtype=torch.float32)
print(h)
l = torch.randint(0,100,(3,3,3),dtype=torch.float32)
print(l)

tensor([[71., 98., 27.],
        [43., 89., 42.],
        [ 0., 41., 24.]])
tensor([[[37., 14., 31.],
         [31., 42., 82.],
         [35., 94.,  7.]],

        [[74., 71., 10.],
         [37., 11., 76.],
         [90., 17., 19.]],

        [[40., 96., 94.],
         [44., 39., 63.],
         [30.,  0., 69.]]])


In [ ]:
# Determinant of Tensor
print(h.det())
print(torch.det(h))
print(l.det())
print(torch.det(l))

tensor(-24141.0020)
tensor(-24141.0020)
tensor([-192412.0000,  351975.0312, -112356.0078])
tensor([-192412.0000,  351975.0312, -112356.0078])


In [ ]:
# Inverse of Tensor
print(h.inverse())
print(torch.inverse(h))
print(l.inverse())
print(torch.inverse(l))

tensor([[-0.0171,  0.0516, -0.0710],
        [ 0.0427, -0.0706,  0.0754],
        [-0.0730,  0.1206, -0.0872]])
tensor([[-0.0171,  0.0516, -0.0710],
        [ 0.0427, -0.0706,  0.0754],
        [-0.0730,  0.1206, -0.0872]])
tensor([[[ 0.0385, -0.0146,  0.0008],
         [-0.0138,  0.0043,  0.0108],
         [-0.0075,  0.0155, -0.0058]],

        [[-0.0031, -0.0033,  0.0150],
         [ 0.0174,  0.0014, -0.0149],
         [-0.0010,  0.0146, -0.0052]],

        [[-0.0240,  0.0590, -0.0212],
         [ 0.0102,  0.0005, -0.0144],
         [ 0.0104, -0.0256,  0.0237]]])
tensor([[[ 0.0385, -0.0146,  0.0008],
         [-0.0138,  0.0043,  0.0108],
         [-0.0075,  0.0155, -0.0058]],

        [[-0.0031, -0.0033,  0.0150],
         [ 0.0174,  0.0014, -0.0149],
         [-0.0010,  0.0146, -0.0052]],

        [[-0.0240,  0.0590, -0.0212],
         [ 0.0102,  0.0005, -0.0144],
         [ 0.0104, -0.0256,  0.0237]]])


### Comparison Operations

In [ ]:
i = torch.randint(0,50,(2,3))
j = torch.randint(0,50,(2,3))
print(i)
print(j)

tensor([[29, 34,  0],
        [18,  1, 19]])
tensor([[48, 28, 11],
        [ 3, 39, 34]])


In [ ]:
# Greater Than
print(i > j)
# less than
print(i < j)
# Equal to
print(i == j)
# Not Equal to
print(i != j)
# Greator Than Equal to
print(i >= j)
# Less than Equal To
print(i <= j)

tensor([[False,  True, False],
        [ True, False, False]])
tensor([[ True, False,  True],
        [False,  True,  True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False,  True, False],
        [ True, False, False]])
tensor([[ True, False,  True],
        [False,  True,  True]])


### Special Functions

In [ ]:
k = torch.randint(0,50,(2,3),dtype=torch.float32)
k

tensor([[34., 33., 32.],
        [27., 31.,  2.]])

In [ ]:
# Log Calculation
print(k.log())
print(torch.log(k))

tensor([[3.5264, 3.4965, 3.4657],
        [3.2958, 3.4340, 0.6931]])
tensor([[3.5264, 3.4965, 3.4657],
        [3.2958, 3.4340, 0.6931]])


In [ ]:
# Exponents Calculation
print(k.exp())
print(torch.exp(k))

tensor([[5.8346e+14, 2.1464e+14, 7.8963e+13],
        [5.3205e+11, 2.9049e+13, 7.3891e+00]])
tensor([[5.8346e+14, 2.1464e+14, 7.8963e+13],
        [5.3205e+11, 2.9049e+13, 7.3891e+00]])


In [ ]:
# Square Roots Calculation
print(k.sqrt())
print(torch.sqrt(k))

tensor([[5.8310, 5.7446, 5.6569],
        [5.1962, 5.5678, 1.4142]])
tensor([[5.8310, 5.7446, 5.6569],
        [5.1962, 5.5678, 1.4142]])


In [ ]:
# Sigmoid Calculation - means passing each value through sigmoid function
print(k.sigmoid())
print(torch.sigmoid(k))

tensor([[1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 0.8808]])
tensor([[1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 0.8808]])


In [ ]:
# Softmax Calculation for each value Column Wise
print(k.softmax(dim=0))
print(torch.softmax(k, dim=0))
# Softmax Calculation for each value Row Wise
print(k.softmax(dim=1))
print(torch.softmax(k, dim=1))

tensor([[9.9909e-01, 8.8080e-01, 1.0000e+00],
        [9.1105e-04, 1.1920e-01, 9.3576e-14]])
tensor([[9.9909e-01, 8.8080e-01, 1.0000e+00],
        [9.1105e-04, 1.1920e-01, 9.3576e-14]])
tensor([[6.6524e-01, 2.4473e-01, 9.0031e-02],
        [1.7986e-02, 9.8201e-01, 2.4979e-13]])
tensor([[6.6524e-01, 2.4473e-01, 9.0031e-02],
        [1.7986e-02, 9.8201e-01, 2.4979e-13]])


In [ ]:
# Relu Calculation
print(k.relu())
print(torch.relu(k))

tensor([[34., 33., 32.],
        [27., 31.,  2.]])
tensor([[34., 33., 32.],
        [27., 31.,  2.]])


## Inplace Operations
  To do any operation inplace a simple shortcut is to just follow the convention "func_" means "function_name" + "_ UNDERSCORE" (Most Functions have this notation). There are other ways to do the same.

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.6931, 0.4958, 0.1998],
        [0.5541, 0.3350, 0.2367]])
tensor([[0.6311, 0.0590, 0.8348],
        [0.3750, 0.3650, 0.7161]])


In [ ]:
# Simple add
print(m + n)
print(m)
# Inplace Add
print(m.add_(n))
print(m)

tensor([[1.3243, 0.5549, 1.0346],
        [0.9291, 0.7001, 0.9528]])
tensor([[0.6931, 0.4958, 0.1998],
        [0.5541, 0.3350, 0.2367]])
tensor([[1.3243, 0.5549, 1.0346],
        [0.9291, 0.7001, 0.9528]])
tensor([[1.3243, 0.5549, 1.0346],
        [0.9291, 0.7001, 0.9528]])


In [ ]:
# Inplace Relu Example
print(m.relu_())
print(m)

tensor([[1.3243, 0.5549, 1.0346],
        [0.9291, 0.7001, 0.9528]])
tensor([[1.3243, 0.5549, 1.0346],
        [0.9291, 0.7001, 0.9528]])


## Copy Operations

In [ ]:
p = torch.rand(2,3)
q = torch.rand(2,3)
print(p)
print(q)

tensor([[0.5505, 0.2181, 0.1614],
        [0.2648, 0.2201, 0.2969]])
tensor([[0.9315, 0.7105, 0.4754],
        [0.9855, 0.4474, 0.6525]])


In [ ]:
# Simple Copy (Reference or Alias Approach)
p = q
p[0][0]=1
print(p)
print(q)

tensor([[1.0000, 0.7105, 0.4754],
        [0.9855, 0.4474, 0.6525]])
tensor([[1.0000, 0.7105, 0.4754],
        [0.9855, 0.4474, 0.6525]])


In [ ]:
# Real Cloning
p = q.clone()
p[0][0]=5
print(p)
print(q)

tensor([[5.0000, 0.7105, 0.4754],
        [0.9855, 0.4474, 0.6525]])
tensor([[1.0000, 0.7105, 0.4754],
        [0.9855, 0.4474, 0.6525]])


## Reshaping Tensors

In [ ]:
z = torch.ones(4,4)
print(z)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
# .reshape function
# Most Important thing for reshape function is that the product of
# shape of the original tensor (4*4 = 16) must be equal to the product
# of shape elements of reshaped tensor (2*2*2*2 = 16)
z.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# .flatten function
# This converts complete tensor into 1 dimension
z.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
z2 = torch.rand(2,3,4)
print(z2)

tensor([[[0.5432, 0.2732, 0.1899, 0.0129],
         [0.4990, 0.2865, 0.9242, 0.1868],
         [0.9841, 0.3884, 0.4349, 0.1585]],

        [[0.9209, 0.1262, 0.8714, 0.3838],
         [0.1766, 0.4939, 0.6558, 0.1180],
         [0.2845, 0.8290, 0.3586, 0.0016]]])


In [ ]:
# Permuting Tensor means reshaping by changing the positions of specific
# dimensions
print(z2.permute(2,0,1))
print(z2.permute(2,0,1).shape)

tensor([[[0.5432, 0.4990, 0.9841],
         [0.9209, 0.1766, 0.2845]],

        [[0.2732, 0.2865, 0.3884],
         [0.1262, 0.4939, 0.8290]],

        [[0.1899, 0.9242, 0.4349],
         [0.8714, 0.6558, 0.3586]],

        [[0.0129, 0.1868, 0.1585],
         [0.3838, 0.1180, 0.0016]]])
torch.Size([4, 2, 3])


In [ ]:
# .unsqueeze Method
# This adds a new dimension at our desired place
img = torch.rand(226,226,3)
print(img.unsqueeze(0).shape)
print(img.unsqueeze(2).shape)
print(img.unsqueeze(1).shape)

torch.Size([1, 226, 226, 3])
torch.Size([226, 226, 1, 3])
torch.Size([226, 1, 226, 3])


In [ ]:
# .squeeze Method
# This removes a specific dimension from our desired place
img2 = torch.rand(1,20)
print(img2.squeeze(0).shape)

torch.Size([20])


## Numpy and Tensor Interchangeability

In [ ]:
a1 = torch.rand(2,3)
print(a1)
print(type(a1))
n1 = a1.numpy()
print(n1)
print(type(n1))
a2 = torch.from_numpy(n1)
print(a2)
print(type(a2))

tensor([[0.1334, 0.2258, 0.8138],
        [0.1992, 0.1994, 0.0500]])
<class 'torch.Tensor'>
[[0.13338321 0.22583932 0.81383   ]
 [0.19916278 0.19935793 0.05004328]]
<class 'numpy.ndarray'>
tensor([[0.1334, 0.2258, 0.8138],
        [0.1992, 0.1994, 0.0500]])
<class 'torch.Tensor'>
